name: test

on: [
  push,
  # Too expensive with ~20m build times.
  # pull_request
]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '18', '20']

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm run lint

    - name: install & start PostgreSQL with PostGIS
      # pin to commit that changes it to use the postgis/postgis Docker image, which we need for PostgreSQL version 14
      uses: huaxk/postgis-action@0e3a7a41c0b06b9a1fe690d937f21168af8839bd
      with:
        postgresql password: password
        postgresql user: postgres
        postgresql db: postgres
        postgresql version: '14-3.2-alpine'

    - name: install & start Redis
      uses: supercharge/redis-github-action@1.8.0
      # with:
      #   redis-version: ${{ matrix.redis-version }}

    - name: start NATS Streaming
      run: |
        docker run -d -p 4222:4222 -p 8222:8222 nats-streaming

    - name: npm test
      run : npm test
      env:
        PGHOST: localhost
        PGPORT: '5432'
        PGUSER: postgres
        PGPASSWORD: password
        PGDATABASE: postgres
